LROOT = ../../..

D = graph_alg
#L = G
L = leda

include ../../Make.src

TEMPDIR = $(LROOT)/incl/LEDA/graph/templates

_max_flow$(o):      $(TEMPDIR)/max_flow.h
_dijkstra$(o):      $(TEMPDIR)/dijkstra.h
_shortest_path$(o): $(TEMPDIR)/shortest_path.h
_mwb_matching$(o):  $(TEMPDIR)/mwb_matching.h
_mw_matching$(o):   $(TEMPDIR)/mw_matching.h

