#.PHONY: install_apps

WFLAGS = -DWINMAIN

LROOT   = ../..
#UNIXLIB = -lleda $(XLIB) -lm -lssl -lcrypto
UNIXLIB = -lleda $(XLIB)
DOSLIB  = ..\\..\\leda.lib $(XLIB)
DOSLIB1 = ..\\..\\GeoWin.lib

include ../Make.pro

